### ISSUE TITLE
Missing services: docker-based service?

### ISSUE THREAD

**Issue by galeone** [galeone/bacup#11]
Let's say we have a containerized service made in this way:

- webserver (Nginx) 
- backend (PHP)
- database1 (PostgreSQL)
- database2 (Redis)
- frontend (HTML,CSS, js, ...)

All these services are inside a docker container, and they are configurable through configuration files often mounted inside a volume.

Doing the backup of the configuration files is easy: we can just use the "folders" service.

But what about the data of the different databases? We could use the folders service and copy and archive all of them, but if the database is in use (and it's often the case), there's a non-zero chance of copying some file that's in a nonstable state.

Hence, the possibility of invoking the correct commands on the container should be provided, in order to ask the running DB to do the dump, store it inside the volume (accessible from the host), and then back up the correctly created dump.

An interface for being compatible with docker should be defined.

**Comment by dantepippi** [comment]
Maybe a feature where the user could set a script and a data destination folder on the configuration file. The script would be run before the backup job. This would make the solution flexible and work with any service (bare metal or docker). The user would create scripts (works for bare metal or docker services) to dump the desired data (also defining the service behavior, as stopping it or not). After the script runs successfully it would only be required to backup the destination folder. Some failure/retry logic would be required.

**Comment by galeone** [comment]
It makes sense!

Anyway, I'm referring to a typical scenario of backing up the data of a web application containerized. For example, this is the application I want to backup (the original reason because I created bacup is for backing up this website - I lost 1 year of data on it).

https://github.com/nerdzeu/docker/blob/master/docker-compose.yml

Some really good feature of bacup would be the possibility of being integrated with docker-compose. 2 options:

1. Reading the docker-compose from the outside (the host), parse it, understand what the user wants to backup (e.g. the postgres db)
2. Being used directly as a service inside docker-compose
