### ISSUE TITLE
Missing remotes: git

### ISSUE THREAD

**Issue by galeone** [galeone/bacup#8]
It's a very strange way of doing backup, but it's something I've already seen (and done, shame on me).

If a local folder is a git repository, then we can basically do:

```bash
git checkout <backup-branch> # optional?
git add . -A
git commit -m 'backup'
git push origin
```

Using SSH is mandatory, hence we can re-use the private key control part of the [SSH remote](https://github.com/galeone/bacup/blob/main/src/remotes/ssh.rs) + adding the `which(git)` and be sure that `git` is installed in the system, and create a new type that implements the `Uploader` trait and it behaves similarly to the SSH service.

The support for backing up compressed files and compressed folders can be added too, although it's horrific loading archives on Git (especially for backing up). But anyway, it's a feature we can offer just in case.

**Comment by dantepippi** [comment]
Just to clarify, do you mean to use git as a backup solution or is it meant to backup git repos?

**Comment by galeone** [comment]
> Just to clarify, do you mean to use git as a backup solution or is it meant to backup git repos?

In my particular scenario, I have a project that generates in place (inside the git folder) some content (think about a static website, with automatically generated articles). I had the need to backup them once they are generated, and since they are generated directly inside the repo, I just do `git add .` and commit them.

Anyway, the solution should be general.

The `uploader` trait has 4 cases:

- upload_folder -> move all the files into the repo (if they are not there yet), and `git add .; git commit -m 'backup'; git push origin`
- upload_file ->  move this file into the repo (and as above)
- upload_file_compressed -> same as upload_file, but the file is first compressed, then moved inside the repo
- upload_folder_compressed -> compress a folder, move it inside the repo, and commit it
